CREATE TABLE IF NOT EXISTS warehouse (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address TEXT,
    type VARCHAR(50) NOT NULL CHECK (type IN ('CENTRAL', 'REMOTE')),
    active BOOLEAN NOT NULL DEFAULT TRUE
);
